###

GET http://localhost:3000/convocados

###

POST http://localhost:3000/convocacao
Content-Type: application/json

{
    "nome": "Neymar",
    "posicao": "PE"
}

###

PUT http://localhost:3000/convocacao/1
Content-Type: application/json

{
    "nome": "ENDRICK",
    "posicao": "ATA"
}

###

DELETE http://localhost:3000/convocacao/1